<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<!-- windows10.0.19041.0 required for SpatialAudioFormatSubtype.DolbyAtmosForHeadphones and IsSpatialAudioFormatSupported APIs -->
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<ApplicationIcon>Resources\streamtweak.ico</ApplicationIcon>
		<Version>5.4.0</Version>
		<AssemblyVersion>5.4.0.0</AssemblyVersion>
		<FileVersion>5.4.0.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\streammodeko.ico" />
		<None Remove="Resources\streamtweak.ico" />
		<None Remove="Resources\Twemoji\*.png" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\streamtweak.png"/>
<Resource Include="Resources\Twemoji\globe_3d.png"/>
		<Resource Include="Resources\Twemoji\desktop_3d.png"/>
		<Resource Include="Resources\Twemoji\headphones_3d.png"/>
		<Resource Include="Resources\Twemoji\card_index_dividers_3d.png"/>
		<Resource Include="Resources\Twemoji\video_game_3d.png"/>
		<Resource Include="Resources\Twemoji\clipboard_3d.png"/>
		<Resource Include="Resources\Twemoji\open_book_3d.png"/>
		<Resource Include="Resources\Twemoji\link_3d.png"/>
		<Resource Include="Resources\Twemoji\bar_chart_3d.png"/>
		<Resource Include="Resources\Twemoji\credit_card_3d.png"/>
		<Resource Include="Resources\Twemoji\warning_3d.png"/>
		<Resource Include="Resources\Twemoji\gear_3d.png"/>
		<Resource Include="Resources\Twemoji\satellite_3d.png"/>
		<Resource Include="Resources\Twemoji\trophy_3d.png"/>
		<Resource Include="Resources\Twemoji\wrench_3d.png"/>
		<Resource Include="Resources\Twemoji\rainbow_3d.png"/>
		<Resource Include="Resources\Twemoji\high_voltage_3d.png"/>
		<Resource Include="Resources\Twemoji\television_3d.png"/>
		<Resource Include="Resources\Twemoji\play_button_3d.png"/>
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\streammodeko.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\streamtweak.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\streammodeok.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11" />
		<PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
	</ItemGroup>

</Project>
